gradle-8.14.3 uplift
      sonarqube_plugin_version = '7.3.1.8318'
      jacoco_tool_version = '0.8.6'

      springBootVersion = '3.5.16'

      hapiFhirVersion = '8.8.1'

deal with transitive dependency issue:

   implementation(group: 'ca.uhn.hapi.fhir', name: 'hapi-fhir-spring-boot-autoconfigure', version: hapiFhirVersion) {

      /*This keeps the needed HAPI autoconfigure classes for compile-time, while preventing it from pulling Spring Boot 3.5.x and related transitive jars that were overriding your intended 3.2.0 stack and causing NoClassDefFoundError: org/apache/hc/client5/http/ssl/TlsSocketStrategy. */
      transitive = false
   }